#!/bin/bash -l

#Enable bash history
HISTFILE=/root/.bash_history
set -o history

# Generate creds against 3mTTL role
vault read oracle_vault/creds/3mTTL

# Generate creds against 1hTTL role
vault read oracle_vault/creds/1hTTL

exit 0
